// AutoGenerated file for ChatScreenScreen
// generate date: 16/10/24 08:01 PM

import 'package:flutter/cupertino.dart';
import 'chat_screen_screen_builder.dart';


/// Created by Abdullah on 16/10/24 08:01 PM.

class ChatScreenScreen extends StatelessWidget {

  const ChatScreenScreen({super.key,});
  @override
  Widget build(BuildContext context) {
    return const ChatScreenScreenBuilder();
  }
}
