name: Deploy Flutter Web to Namecheap
on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Deploy to Namecheap
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build web project
      - name: Build Flutter Web
        run: |
          flutter build web
          mkdir -p build/web/assets

      # Step 5: Deploy to Namecheap FTP
      - name: Deploy to Namecheap
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.globalfreelancepay.com
          username: globipay@admin.globalfreelancepay.com
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          local-dir: ./build/web/
          server-dir: /
          protocol: ftp
          port: 21
          security: loose
          timeout: 90000
          dry-run: false
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/.dart_tool/**
            **/.idea/**
            **/.vscode/**