name: Publish Website to CPanel
on:
  push:
    branches:
      - production
jobs:
  SFTP-Deploy-Action:
    name: SFTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # Set up Flutter environment with the recommended version
      - name: Set up Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
      
      # Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get
        
      # Build the Flutter project for the web
      - name: Build Flutter Web Project
        run: flutter build web
        
      # Deploy using SFTP
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.PROD_FTP_USERNAME }}
          server: ${{ secrets.PROD_FTP_SERVER }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          local_path: './build/web/*'
          remote_path: '/admin.globalfreelancepay.com'
          sftpArgs: '-o StrictHostKeyChecking=no'
