name: Publish Website to CPanel
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # Set up Flutter environment with a specific version
      - name: Set up Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'  # Specify the Flutter version here

      # Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build the Flutter project for the web
      - name: Build Flutter Web Project
        run: flutter build web

      # Deploy to FTP server
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/web/  # Built web files from Flutter
          server-dir: /public_html/globipay_admin_panel/  # Destination on the server
          debug: true  # Optional: Add debug for more detailed logs
