name: Publish Website to CPanel
on:
  push:
    branches:
      - production
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web Project
        run: flutter build web

      - name: Deploy to Namecheap FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.PROD_FTP_SERVER }}
          username: ${{ secrets.PROD_FTP_USERNAME }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          local-dir: build/web/
          server-dir: /admin/
          protocol: ftps  # ✅ Use FTPS instead of plain FTP
          passive: true   # ✅ Required for shared hosting
          security: loose # ✅ Prevents strict SSL verification issues
          timeout: 60000  # ✅ Prevents timeout issues
          concurrency: 1  # ✅ Prevents connection limits from causing failures
